GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title":"Blog 1",
    "author":"Sylvester Dsouza",
    "url":"http://sylvester.dsouza",
    "likes":5
}